{"name": "test_call_api_with_request_exception", "status": "passed", "description": "测试其他请求异常", "start": 1761614695588, "stop": 1761614695589, "uuid": "b72f1810-7f0d-498c-8085-5d4aad34cced", "historyId": "28e47c931330d82774324f748594c5cc", "testCaseId": "2532cf44094b7203baeed05bfb78f89f", "fullName": "testcases.test_error_response.TestCallApi#test_call_api_with_request_exception", "labels": [{"name": "parentSuite", "value": "testcases"}, {"name": "suite", "value": "test_error_response"}, {"name": "subSuite", "value": "TestCallApi"}, {"name": "host", "value": "DESKTOP-SQEMBVG"}, {"name": "thread", "value": "15580-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.test_error_response"}]}