{"name": "test_error_handling", "status": "passed", "description": "测试错误处理", "start": 1761614700932, "stop": 1761614702717, "uuid": "b54905a8-d19d-4136-96e4-47f614949d98", "historyId": "b1e99c6105277b6172bf5d21f8e08f45", "testCaseId": "16b60198316134c37da13a21dd689bc4", "fullName": "testcases.test_placeholder_api.Test_api#test_error_handling", "labels": [{"name": "parentSuite", "value": "testcases"}, {"name": "suite", "value": "test_placeholder_api"}, {"name": "subSuite", "value": "Test_api"}, {"name": "host", "value": "DESKTOP-SQEMBVG"}, {"name": "thread", "value": "15580-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.test_placeholder_api"}]}