{"name": "test_call_api_with_error_status_codes[404-API调用失败：404 Client Error]", "status": "passed", "description": "测试各种HTTP错误状态码", "parameters": [{"name": "status_code", "value": "404"}, {"name": "expected_exception_msg", "value": "'API调用失败：404 Client Error'"}], "start": 1761614695541, "stop": 1761614695544, "uuid": "909a40ff-3cce-4962-8fc4-3155fc78c18c", "historyId": "60dfff999bc09e395321441b7d215012", "testCaseId": "0ba28f683659835500083ccde95cdb5e", "fullName": "testcases.test_error_response.TestCallApi#test_call_api_with_error_status_codes", "labels": [{"name": "parentSuite", "value": "testcases"}, {"name": "suite", "value": "test_error_response"}, {"name": "subSuite", "value": "TestCallApi"}, {"name": "host", "value": "DESKTOP-SQEMBVG"}, {"name": "thread", "value": "15580-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.test_error_response"}]}